"""add attachments table for extended content storage

Revision ID: 80299ea4a74e
Revises: afd00efbd06b
Create Date: 2025-10-04 20:55:22.396461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '80299ea4a74e'
down_revision: Union[str, None] = 'afd00efbd06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_created_at'), 'attachments', ['created_at'], unique=False)
    op.create_index(op.f('idx_attachment_id'), 'attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_attachment_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_created_at'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
